#server :
#  port : 8001

spring :
  application :
    name : players-service
  config:
    import : "optional: configserver:http://localhost:8000"


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true


