server:
  port : 9000


#getting all configuration from here itself
spring:
  profiles:
    active: native
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

