server :
  port : 8220

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring :
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**

        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**

        - id: QUESTION-SERVICE
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/question/**
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quiz/**